### PR TITLE
Root readme

### PR DESCRIPTION
**Pull request by 3v0k4**
Light:

Screenshot 2022-11-09 at 10 21 24

Dark:

Screenshot 2022-11-09 at 10 20 33

### CODE REVIEW

**Comment by pavanjadhaw** [comment]
I think we can move screenshot and logo image files to `.github/assets` or similar instead of keeping them at the root

**Comment by 3v0k4** [comment]
@pavanjadhaw I should get an updated screenshot today. I'll move things as you proposed then.

**Comment by 3v0k4** [comment]
I decided not to wait for the screenshot so we can merge this now. I'll add it later together with the [social media preview image](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview).

This is ready for review/merge cc @smeijer @unamashana

**Comment by unamashana** [comment]
@3v0k4 I believe the first few lines in the README should be about what this public repo is for

* Discussions for support/questions on the API and SDKs, changelog, and roadmap
* Public assets
  * OpenAPI 
  * Docs 
* PRs for public assets

We can then link to other pages.  We should also add a note to email hello@magicbell.io or use the support form for any account specific support requests.

**Review by unamashana — APPROVED** [review]

**Pull request merged**
